# USER SIGN IN
POST  http://localhost:5000/api/signup
Content-Type: application/json

{
    "name": "Bhargab",
    "phone": "9365698129",
    "latitude": "91.7635072",
    "longitude": "26.158694399999998" 
}

# POST  http://localhost:3000/api/verifyOTP
# Content-Type: application/json

# {
#     "phone": "9365698129",
# }

# Admin Signup
# POST  http://localhost:5000/api/admin/signup
# Content-Type: application/json

# {
#     "name": "Bhargab Nath",
#     "phone": "9365698129",
#     "role": 1,
#     "latitude": "91.7635072",
#     "longitude": "26.158694399999998" 
# }

#  POST  http://localhost:3000/api/admin/verifyOTP
# Content-Type: application/json

# {
#     "name": "Bhargab Nath",
#     "phone": "9365698129",
#     "role": 1,
#     "code": "123456"
# }

# POST http://localhost:5000/api/get/locations
# Content-Type: application/json

# {
#     "latitude": 26.5260594,
#     "longitude": 90.7961624
# }